# Generated by Django 5.1.2 on 2024-10-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tags_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='core.tags', verbose_name='Tags'),
        ),
    ]
